"""Minimal type stubs for the FreeCAD Python API.

FreeCAD is not a pip-installable package: it ships its own interpreter with
``FreeCAD`` and ``FreeCADGui`` built in.  These stubs exist purely so a type
checker can resolve the imports and flag real mistakes in the surrounding code;
they are never imported at runtime.

Only the surface MrFreeTool actually touches is declared.  Everything is
permissive on purpose - the real API is a C++ binding whose types vary between
releases, and pretending to know them more precisely than we do would produce
false confidence.
"""

from typing import Any, List, Optional, Sequence

# ---------------------------------------------------------------------------
# FreeCAD
# ---------------------------------------------------------------------------
class Console:
    @staticmethod
    def PrintMessage(text: str) -> None: ...
    @staticmethod
    def PrintError(text: str) -> None: ...
    @staticmethod
    def PrintWarning(text: str) -> None: ...
    @staticmethod
    def PrintLog(text: str) -> None: ...

class Document:
    Name: str
    Label: str
    FileName: str
    Objects: List[Any]
    ActiveObject: Any

    def getObject(self, name: str) -> Optional[Any]: ...
    def addObject(self, type_id: str, name: str = "", **kwargs: Any) -> Any: ...
    def removeObject(self, name: str) -> None: ...
    def recompute(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self) -> Any: ...
    def saveAs(self, path: str) -> Any: ...
    def getDependentDocuments(self) -> List[Any]: ...
    def setExpression(self, path: str, expression: str) -> None: ...
    @property
    def OutList(self) -> List[Any]: ...

class ParameterGroup:
    def Get(self, key: str, default: Any = None) -> Any: ...
    def GetInt(self, key: str, default: int = 0) -> int: ...
    def GetFloat(self, key: str, default: float = 0.0) -> float: ...
    def GetBool(self, key: str, default: bool = False) -> bool: ...
    def GetString(self, key: str, default: str = "") -> str: ...
    def SetInt(self, key: str, value: int) -> None: ...
    def SetFloat(self, key: str, value: float) -> None: ...
    def SetBool(self, key: str, value: bool) -> None: ...
    def SetString(self, key: str, value: str) -> None: ...
    def RemInt(self, key: str) -> None: ...
    def GetFloats(self, key: str) -> List[float]: ...
    def SetFloats(self, key: str, values: Sequence[float]) -> None: ...

def ParamGet(path: str) -> ParameterGroup: ...
def getUserAppDataDir() -> str: ...
def getResourceDir() -> str: ...
def getHomePath() -> str: ...
def saveParameter() -> None: ...
def newDocument(name: str = "") -> Document: ...
def openDocument(path: str) -> Document: ...
def closeDocument(name: str) -> None: ...

#: The open document, or ``None`` when nothing is open.
ActiveDocument: Optional[Document]
